from __future__ import annotations
from dataclasses import dataclass
from typing import Any, Protocol

@dataclass
class ProjectHandle:
    session_id: str
    project_id: str
    path: str
    readonly: bool = True

class LumericalAdapter(Protocol):
    name: str
    def status(self) -> dict[str, Any]: ...
    def open_project(self, path: str, readonly: bool = True) -> ProjectHandle: ...
    def list_objects(self, project_id: str) -> list[dict[str, Any]]: ...
    def list_properties(self, project_id: str, object_name: str) -> list[str]: ...
    def get_property(self, project_id: str, object_name: str, property_name: str) -> dict[str, Any]: ...
    def set_property(self, project_id: str, object_name: str, property_name: str, value: Any) -> dict[str, Any]: ...
    def run(self, project_id: str, timeout_sec: int = 3600) -> dict[str, Any]: ...
    def get_monitor_result(self, project_id: str, monitor_name: str, result_name: str) -> dict[str, Any]: ...
    def close(self, session_id: str) -> dict[str, Any]: ...
