from __future__ import annotations
from dataclasses import dataclass
from typing import Any, Protocol

@dataclass
class ProjectHandle:
    session_id: str
    project_id: str
    path: str
    readonly: bool = True

class LumericalAdapter(Protocol):
    name: str
    def status(self) -> dict[str, Any]: ...
    def open_project(self, path: str, readonly: bool = True) -> ProjectHandle: ...
    def new_project(self) -> ProjectHandle: ...
    def save_project_as(self, project_id: str, path: str, overwrite: bool = False) -> dict[str, Any]: ...
    def add_fdtd_region(self, project_id: str, name: str, properties: dict[str, Any] | None = None) -> dict[str, Any]: ...
    def add_rectangle(self, project_id: str, name: str, properties: dict[str, Any] | None = None) -> dict[str, Any]: ...
    def add_dipole_source(self, project_id: str, name: str, properties: dict[str, Any] | None = None) -> dict[str, Any]: ...
    def add_power_monitor(self, project_id: str, name: str, properties: dict[str, Any] | None = None) -> dict[str, Any]: ...
    def delete_object(self, project_id: str, object_name: str) -> dict[str, Any]: ...
    def list_objects(self, project_id: str) -> list[dict[str, Any]]: ...
    def list_properties(self, project_id: str, object_name: str) -> list[str] | dict[str, Any]: ...
    def get_property(self, project_id: str, object_name: str, property_name: str) -> dict[str, Any]: ...
    def set_property(self, project_id: str, object_name: str, property_name: str, value: Any) -> dict[str, Any]: ...
    def run(self, project_id: str, timeout_sec: int = 3600) -> dict[str, Any]: ...
    def get_monitor_result(self, project_id: str, monitor_name: str, result_name: str) -> dict[str, Any]: ...
    def close_project(self, project_id: str) -> dict[str, Any]: ...
    def close(self, session_id: str) -> dict[str, Any]: ...
